# .github/workflows/deploy.yml
name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  APP_ID: ${{ secrets.GCP_APPLICATION }}
  RUN_REGION: europe-west3
  SA_KEY_JSON: ${{ secrets.GCP_SA_KEY_JSON }}
  STORAGE_NAME: ${{ secrets.GCP_STORAGE_NAME }}

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'deploy')"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: $PROJECT_ID
          service_account_key: $SA_KEY_JSON

      # Configure Docker with Credentials
      - name: Configure Docker
        run: gcloud auth configure-docker

      # Build Docker image
      - name: Build
        # use --gcs-log-dir to allow log streaming
        run: gcloud builds submit --gcs-log-dir gs://$STORAGE_NAME/cloud_run_log_build --tag gcr.io/$PROJECT_ID/$APP_ID:${{ github.sha }}
      
      # Deploy Docker image
      - name: Deploy
        run: |-
          gcloud run deploy $APP_ID \
            --region $RUN_REGION \
            --image gcr.io/$PROJECT_ID/$APP_ID:${{ github.sha }} \
            --platform "managed" \
            --allow-unauthenticated
